version: "3.8"

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.3
    container_name: redpanda
    command:
      - redpanda
      - start
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr=internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr=internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr=internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr=internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr=redpanda:33145
      - --advertise-rpc-addr=redpanda:33145
      - --smp=1
      - --memory=1G
      - --mode=dev-container
      - --default-log-level=info
    ports:
      - "18081:18081" # Schema registry
      - "18082:18082" # HTTP Proxy
      - "19092:19092" # Kafka API
      - "19644:9644" # Admin API
    healthcheck:
      test:
        ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s

  console:
    image: docker.redpanda.com/redpandadata/console:v2.4.5
    container_name: redpanda-console
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
        connect:
          enabled: false
    ports:
      - "8080:8080"
    depends_on:
      redpanda:
        condition: service_healthy

  # Initialize topics
  topic-init:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.3
    container_name: topic-init
    entrypoint: /bin/sh
    command: -c "
      echo 'Waiting for Redpanda to be ready...';
      while ! rpk cluster health --brokers redpanda:9092 | grep -q 'Healthy.*true'; do
      sleep 2;
      done;
      echo 'Creating topics...';
      rpk topic create test-topic --brokers redpanda:9092 --partitions 6 --replicas 1;
      rpk topic create load-test --brokers redpanda:9092 --partitions 12 --replicas 1;
      echo 'Topics created successfully';
      "
    depends_on:
      redpanda:
        condition: service_healthy
